version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: schedule-db
    restart: always
    environment:
      POSTGRES_DB: schedule
      POSTGRES_USER: schedule_server
      POSTGRES_PASSWORD: schedule_server_secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - schedule-network

networks:
  schedule-network:

volumes:
  pgdata:
