version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wss-db
    restart: always
    environment:
      POSTGRES_DB: wss_db
      POSTGRES_USER: wss_server
      POSTGRES_PASSWORD: wss_secret
    ports:
      - "5433:5432"
    volumes:
      - wssdata:/var/lib/postgresql/data
    networks:
      - wss-network

networks:
  wss-network:

volumes:
  wssdata:
